<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <RootNamespace>Xwt.Gtk4</RootNamespace>
    <AssemblyName>Xwt.Gtk4</AssemblyName>
    <LangVersion>8</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DefineConstants>TRACE;DEBUG;XWT_GTK4</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineConstants>TRACE;RELEASE;XWT_GTK4</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xwt\Xwt.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GirCore.Gtk-4.0" Version="0.7.0" />
    <PackageReference Include="GirCore.Gio-2.0" Version="0.7.0" />
    <PackageReference Include="GirCore.GLib-2.0" Version="0.7.0" />
    <PackageReference Include="GirCore.Pango-1.0" Version="0.7.0" />
    <PackageReference Include="GirCore.PangoCairo-1.0" Version="0.7.0" />
    <PackageReference Include="GirCore.Cairo-1.0" Version="0.7.0" />
    <PackageReference Include="GirCore.GdkPixbuf-2.0" Version="0.7.0" />
    <PackageReference Include="GirCore.Graphene-1.0" Version="0.7.0" />
  </ItemGroup>
</Project>
